// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError =
  | { kind: "Database"; message: string }
  | { kind: "Concurrency"; message: string }
  | { kind: "TauriSystem"; message: string };

export type DeleteParams = { id: number };

export type Expense = {
  id: number;
  date: string;
  category: string;
  amount: number;
};

export type ExpenseDateFilter = { startDate: string; endDate: string };

export type ExpenseForCreate = {
  date: string;
  category: string;
  amount: number;
};

export type ListParams<F> = { data: F };

export type MonthSummary = { month: string; expenses: number };
