// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteParams = { id: number, };

export type Expense = { id: bigint, date: string, category: string, amount: number, };

export type ExpenseDateFilter = { startDate: string, endDate: string, };

export type ExpenseForCreate = { date: string, category: string, amount: number, };

export type ListParams<F> = { data: F, };
